name: at_your_home_partner
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.0
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.2
  infinite_scroll_pagination: ^3.2.0
  date_picker_timeline: ^1.2.6
  image_picker: ^1.1.0
  intl: ^0.19.0
  http: ^1.2.1
  cached_network_image: ^3.2.3
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.10
  dropdown_button2: ^2.3.9
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/


  fonts:
    - family: Duplet-Bold.otf
      fonts:
        - asset: assets/fonts/Duplet-Bold.otf

    - family: Duplet-Regular
      fonts:
        - asset: assets/fonts/Duplet-Regular.otf

    - family: Duplet-Semibold
      fonts:
        - asset: assets/fonts/Duplet-Semibold.otf






























